### ISSUE TITLE
org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'authentication' cannot be found on object of type

### ISSUE THREAD

**Issue by chenlinks** [spring-projects/spring-session-bom#129]
org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'authentication' cannot be found on object of type

**Comment by rwinch** [comment]
Can you provide more details on how to reproduce the issue? Also can you explain why you are logging the issue to this repository? This looks more like a spring security problem?

**Comment by eleftherias** [comment]
Closing due to lack of feedback.
