### ISSUE TITLE
Upgrade dependencies to snapshots

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session-bom#182]
This issue is about a general approach to managing a BOM project like this one.

Unless the dependencies to modules that BOM provides are regularly updated to point to the next snapshot versions, the snapshot publication of the BOM itself doesn't make much sense as it will always be the same as the previous stable release.

This is especially important since Spring Boot manages version of Spring Session BOM, so to give a run to something that was recently fixed in Spring Session core modules requires more effort than it really should.

**Comment by eleftherias** [comment]
Thanks @vpavic! I went ahead and made the change on all supported branches.
