### ISSUE TITLE
Upgrade to Spring Session for Apache Geode 3.0.0-M5

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-session-bom#214]
SSDG `3.0.0-M5` is [based on](https://github.com/spring-projects/spring-session-data-geode/blob/3.0.0-M5/gradle.properties#L13) Spring Session `3.0.0-M4` and is [available](https://repo.spring.io/ui/native/milestone/org/springframework/session/spring-session-data-geode/3.0.0-M5/) in the Spring Milestone Repository.

The Spring Session BOM `2022.0.x` BOM needs to be updated accordingly.

**Comment by rwinch** [comment]
Closing in favor of gh-216
