### ISSUE TITLE
Investigate Adding Spring Session Data Geode to Bom

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session-bom#8]
We should validate that Spring Session Data Geode can be added to the BOM w/ Boot and/or Platform Team. If we get the go ahead from the appropriate team(s) we should add it

**Comment by jxblum** [comment]
I went ahead and added `spring-session-data-gemfire` and `spring-session-data-geode` to the Maven BOM file in PR #9.

**Comment by vpavic** [comment]
Closing in favor of #9.
